CREATE TABLE programmer(
  id							INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name  						VARCHAR(150),
  coffee_type_id   				INTEGER,
  paymenth_method_id         	INTEGER,
  timeStarted					LOB,
  timePaid						LOB,
  timeStartedToGetTheCoffe		LOB,
  timeFinished					LOB,
  timeEnterPayQueue				LOB,
  timeLeavePayQueue				LOB,
  timeEnterGetTheCoffeeQueue	LOB,
  timeLeaveGetTheCoffeeQueue	LOB
);

CREATE TABLE statistic(
	machine						VARCHAR(150),
	programmer_id				INTEGER
);

ALTER TABLE statistic
ADD FOREIGN KEY (progammer_id) 
REFERENCES programmer(id)
